### PR TITLE
Beta 1.9 protocol

### PR DESCRIPTION
**Pull request by ghost**
This is primarily for discussion concerning further work representing all the data about blocks as found in the wiki.

New here is a stub showing the representation of the data needed to support different tools behaving differently when used on different blocks.

I have included a prototype entry, showing this additional data in blocks.json (nether block stairs).  Preferred tool is a pick and a sword is damaged more when used on this block. : http://www.minecraftwiki.net/wiki/Stairs.

If this is OK, I'll add entries for the rest of the blocks tomorrow.

### CODE REVIEW

**Comment by ghost** [comment]
One other thing... this includes everything Huin pointed out in the previous request.

**Comment by huin** [comment]
The stairs thing is a bit odd, I didn't realise there were cases where two possible tool types could be used. I'll do a little testing to see what this means.

**Comment by huin** [comment]
Cobblestone stair:

Mined without tool: slow, no item dropped
Mined with stone pickaxe: quick, drops cobblestone (not cobblestone stair)
Mined with wooden sword: slow, no item dropped
Mined with stone sword: slow, no item dropped

I think the wiki is wrong about the sword, the sword has no unusual effect on the block. I think that any tool that has limited durability will lose 2 durability for being used on an inappropriate block. So I shall add a line comment to the suggested values for the stair block with my findings.

**Comment by ghost** [comment]
OK this makes sense.  

However, having just tried a wooden pick (slow and drops a block), we don't have a mechanism for defining if a tool breaks a block quickly or slowly, do we?

**Comment by huin** [comment]
It seems to be implied by the game that if you use the correct tool, then it
is faster. Note that the field ToolRequired being false implies that the
only benefit of using the correct tool is that it is faster. If it is false,
then it is _both_ faster and required to use the correct tool in order to
receive dropped items.

One other bit of information is how long it takes to 'dig' each type of
block (with or without a tool), and but that information does not seem to be
easily available, and so I wouldn't put it in just yet if I were you.

Reason being is that the time to dig a block seems to be a function of the
base block type, and, if the correct tool is used, the material of the tool.
It's also not essential at this time to put these timings in as the client
does this work at the moment. It's just later when it comes to not trusting
clients and preventing speed hacking that will need it.

**Comment by ghost** [comment]
hmm... looking at the wiki for the stone stairs I interpret the tool entry for stone stairs is that a pick axe is preferred and that if a sword is used it gets 2 points of damage. (I get this from the red -2 image in the tool section.)

However, many entries have that -2 sword image with no preferred tool.

Also, if the wiki has no information I will add axe for preferred tool for any block made of wood.  So an axe is preferred for wooden stairs while a pickaxe is preferred for stone, stone brick, brick, and nether stone stairs... for example.

http://www.minecraftwiki.net/wiki/Melon_(Block)
http://www.minecraftwiki.net/wiki/Fence_Gate
http://www.minecraftwiki.net/wiki/Glass_Pane
http://www.minecraftwiki.net/wiki/Huge_Mushroom

next on the list: Redstone ore drops 4 - 6 piles of Redstone dust when mined with a Iron Pickaxe or better.  I suppose these sorts of oddities will have to be dealt with individually.

 I'm wishing the make test_data thingy had more descriptive errors!

**Comment by huin** [comment]
Sounds like it might be the right way to go, but ultimately we need to replicate what the vanilla minecraft does - by testing if necessary.

**Pull request merged**
